Tidy up some formatting and some notices

diff --git a/install/essential b/install/essential
--- a/install/essential
+++ b/install/essential
@@ -13,8 +13,10 @@ is_a_clean_install=false
 # === Check dependencies ===
 # ==========================
 
-if [[ ! $(command -v curl) ]];  then echo "curl is required"; exit 1; fi
-if [[ ! $(command -v git) ]];   then echo "git is required";  exit 1; fi
+if [[ ! $(command -v git) ]]; then
+  echo "git is required"
+  exit 1
+fi
 
 # ========================
 # ===~/.vim/ directory ===
